# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
mono: none
dotnet: 2.0.0

script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet run -c Release -p Axxes.SpaceXLaunchDates.Tests

